In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [6]:
import pandas as pd
df=pd.read_csv(r"D:\Coding\python\Machine learning\pandas\homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
df.bedrooms.median()

4.0

In [8]:
new_df=df.fillna(df.bedrooms.median())
new_df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
from sklearn.linear_model import LinearRegression
import pandas as pd
df=pd.read_csv(r"D:\Coding\python\Machine learning\pandas\homeprices.csv")
reg = LinearRegression()
reg.fit(new_df[['area','bedrooms','age']],df.price)

LinearRegression()

In [10]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
reg.intercept_

221323.00186540408

In [12]:
reg.predict([[3000, 3, 40]])

c:\Users\nischay\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [13]:
reg.predict([[2500, 4, 5]])

c:\Users\nischay\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [14]:
2500*112.06244194+4*23388.88007794+5*-3231.71790863+221323.00186540408

578876.0374840142

In [15]:
3000*112.06244194+3*23388.88007794+40*-3231.71790863+221323.00186540408

498408.2515740241